name: flutter_hackathon
description: Retro typewriter to save the planet

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.4.0+9
  firebase_auth: ^0.16.1
  firebase_storage:
    git:
      url: git://github.com/danysz/flutterfire.git
      ref: master
      path: packages/firebase_storage
  intl: any
  pdf: ^1.3.24
  flutter_full_pdf_viewer: ^1.0.6
  path_provider: ^1.5.1
  shared_preferences: ^0.5.7+3

  cupertino_icons: ^0.1.3
  page_view_indicator: ^2.0.4
  provider: ^4.1.3
  page_turn: ^1.0.1
  audioplayers: ^0.15.1

  google_sign_in: ^4.5.1
  animated_text_kit: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Underwood
      fonts:
        - asset: assets/fonts/uwch.ttf
    - family: Bohemian
      fonts:
        - asset: assets/fonts/bohemian.ttf

  assets:
    - assets/paper/
    - assets/onboarding/
    - assets/login/
    - assets/keyboard/
    - assets/logo/
    - assets/sounds/